# Generated by Django 6.0.5 on 2026-05-25 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_userprofile_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('physician', 'Physician'), ('nurse', 'Nurse'), ('admin', 'Admin'), ('front_desk', 'Front Desk')], max_length=50),
        ),
    ]
