# Generated by Django 6.0.5 on 2026-06-13 19:48

import django.db.models.deletion
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_userprofile_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_name', encrypted_model_fields.fields.EncryptedCharField()),
                ('specialty', encrypted_model_fields.fields.EncryptedCharField(blank=True)),
                ('reason', encrypted_model_fields.fields.EncryptedTextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.patient')),
            ],
        ),
    ]
