'use server';

import { redirect } from 'next/navigation';
import { headers } from 'next/headers';
import { eq } from 'drizzle-orm';
import { controlDb } from '@civica/db/control/client';
import {
  users,
  roles,
  clinicMemberships,
  clinics,
  clinicCodes,
  patientEnrollments,
  patientLinks,
} from '@civica/db/control/schema';
import {
  hashPassword,
  verifyPassword,
  verifyClinicCode,
  hashClinicCode,
  verifyEnrollmentCode,
  createSession,
  getSessionByToken,
  invalidateSession,
  setSessionCookie,
  clearSessionCookie,
  getSessionTokenFromCookies,
} from '@civica/auth';
import { logAuditEvent, AUDIT_ACTIONS } from '@civica/audit';
import { sendWelcomeEmail, sendClinicRegistrationNotification } from '@civica/email';
import { getPlatformSettings } from '@civica/db/control/settings';
import {
  registerSchema,
  loginSchema,
  registerClinicSchema,
  registerPatientSchema,
} from '@/lib/validation/auth';
import { uniqueClinicIdentifiers } from '@/lib/clinics/identifiers';

export interface AuthActionState {
  error?: string;
}

export interface RegisterClinicActionState {
  error?: string;
  success?: boolean;
}

async function getRequestMeta(): Promise<{ ipAddress: string | null; userAgent: string | null }> {
  const headerList = await headers();
  const forwardedFor = headerList.get('x-forwarded-for');
  return {
    ipAddress: forwardedFor ? forwardedFor.split(',')[0].trim() : null,
    userAgent: headerList.get('user-agent'),
  };
}

export async function registerAction(_prevState: AuthActionState, formData: FormData): Promise<AuthActionState> {
  const parsed = registerSchema.safeParse({
    email: formData.get('email'),
    password: formData.get('password'),
    name: formData.get('name'),
    clinicCode: formData.get('clinicCode'),
    requestedRole: formData.get('requestedRole'),
  });

  const { ipAddress, userAgent } = await getRequestMeta();

  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? 'Invalid input' };
  }

  const { email, password, name, clinicCode, requestedRole } = parsed.data;

  await logAuditEvent({
    action: AUDIT_ACTIONS.REGISTER_ATTEMPT,
    resourceType: 'user',
    success: true,
    ipAddress,
    userAgent,
  });

  const clinic = await verifyClinicCode(clinicCode);
  if (!clinic) {
    await logAuditEvent({
      action: AUDIT_ACTIONS.REGISTER_FAILURE,
      resourceType: 'user',
      success: false,
      failureReason: 'invalid_clinic_code',
      ipAddress,
      userAgent,
    });
    return { error: 'Invalid clinic code.' };
  }

  const existingUser = await controlDb.query.users.findFirst({ where: eq(users.email, email) });
  if (existingUser) {
    await logAuditEvent({
      action: AUDIT_ACTIONS.REGISTER_FAILURE,
      clinicId: clinic.id,
      resourceType: 'user',
      success: false,
      failureReason: 'email_taken',
      ipAddress,
      userAgent,
    });
    return { error: 'An account with this email already exists.' };
  }

  const requestedRoleRow = await controlDb.query.roles.findFirst({ where: eq(roles.name, requestedRole) });
  if (!requestedRoleRow) {
    return { error: 'Server is not configured correctly. Please contact support.' };
  }

  const passwordHash = await hashPassword(password);

  const [user] = await controlDb
    .insert(users)
    .values({ email, passwordHash, name })
    .returning();

  await controlDb.insert(clinicMemberships).values({
    userId: user.id,
    clinicId: clinic.id,
    roleId: requestedRoleRow.id,
    status: 'pending',
  });

  await logAuditEvent({
    actorUserId: user.id,
    clinicId: clinic.id,
    action: AUDIT_ACTIONS.REGISTER_SUCCESS,
    resourceType: 'user',
    resourceId: user.id,
    success: true,
    ipAddress,
    userAgent,
  });

  await sendWelcomeEmail(email, name);

  const rawToken = await createSession({ userId: user.id, ipAddress, userAgent });
  await setSessionCookie(rawToken);

  redirect('/dashboard');
}

/**
 * Patient self-registration via a per-patient enrollment code generated by
 * staff in the EMR. The code is the authoritative link to a chart; the email
 * is an additional soft cross-check against the chart on file. On success the
 * account is created, linked to the EMR chart (patient_links), and activated
 * immediately (the code already proves the clinic vouched for this person).
 */
export async function registerPatientAction(
  _prevState: AuthActionState,
  formData: FormData,
): Promise<AuthActionState> {
  const parsed = registerPatientSchema.safeParse({
    enrollmentCode: formData.get('enrollmentCode'),
    name: formData.get('name'),
    email: formData.get('email'),
    password: formData.get('password'),
  });

  const { ipAddress, userAgent } = await getRequestMeta();

  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? 'Invalid input' };
  }

  const { enrollmentCode, name, email, password } = parsed.data;

  await logAuditEvent({
    action: AUDIT_ACTIONS.REGISTER_ATTEMPT,
    resourceType: 'user',
    success: true,
    ipAddress,
    userAgent,
  });

  const enrollment = await verifyEnrollmentCode(enrollmentCode);
  if (!enrollment) {
    await logAuditEvent({
      action: AUDIT_ACTIONS.REGISTER_FAILURE,
      resourceType: 'user',
      success: false,
      failureReason: 'invalid_enrollment_code',
      ipAddress,
      userAgent,
    });
    return { error: 'Invalid or already-used enrollment code.' };
  }

  // Soft cross-check: if the chart has an email on file, it must match.
  if (enrollment.email && enrollment.email.toLowerCase() !== email.toLowerCase()) {
    await logAuditEvent({
      clinicId: enrollment.clinicId,
      action: AUDIT_ACTIONS.REGISTER_FAILURE,
      resourceType: 'user',
      success: false,
      failureReason: 'enrollment_email_mismatch',
      ipAddress,
      userAgent,
    });
    return { error: 'The details you entered do not match our records. Contact your clinic.' };
  }

  const existingUser = await controlDb.query.users.findFirst({ where: eq(users.email, email) });
  if (existingUser) {
    await logAuditEvent({
      clinicId: enrollment.clinicId,
      action: AUDIT_ACTIONS.REGISTER_FAILURE,
      resourceType: 'user',
      success: false,
      failureReason: 'email_taken',
      ipAddress,
      userAgent,
    });
    return { error: 'An account with this email already exists.' };
  }

  const patientRole = await controlDb.query.roles.findFirst({ where: eq(roles.name, 'patient') });
  if (!patientRole) {
    return { error: 'Server is not configured correctly. Please contact support.' };
  }

  const passwordHash = await hashPassword(password);

  const user = await controlDb.transaction(async (tx) => {
    const [user] = await tx.insert(users).values({ email, passwordHash, name }).returning();

    await tx.insert(clinicMemberships).values({
      userId: user.id,
      clinicId: enrollment.clinicId,
      roleId: patientRole.id,
      status: 'active',
    });

    await tx.insert(patientLinks).values({
      userId: user.id,
      clinicId: enrollment.clinicId,
      emrPatientId: enrollment.emrPatientId,
    });

    await tx
      .update(patientEnrollments)
      .set({ status: 'claimed', claimedByUserId: user.id, claimedAt: new Date() })
      .where(eq(patientEnrollments.id, enrollment.id));

    return user;
  });

  await logAuditEvent({
    actorUserId: user.id,
    clinicId: enrollment.clinicId,
    action: AUDIT_ACTIONS.PATIENT_LINK_CREATED,
    resourceType: 'patient_link',
    success: true,
    ipAddress,
    userAgent,
  });

  await sendWelcomeEmail(email, name);

  const rawToken = await createSession({ userId: user.id, ipAddress, userAgent });
  await setSessionCookie(rawToken);

  redirect('/patient-portal');
}

/**
 * Onboards a brand-new clinic. Creates the clinic (status 'pending'), its
 * registration code, and the registrant as that clinic's first clinic_admin
 * -- both the clinic and the membership stay pending until a platform admin
 * approves them from /admin/clinics, which is also when the tenant database
 * is provisioned.
 */
export async function registerClinicAction(
  _prevState: RegisterClinicActionState,
  formData: FormData,
): Promise<RegisterClinicActionState> {
  const parsed = registerClinicSchema.safeParse({
    clinicName: formData.get('clinicName'),
    clinicCode: formData.get('clinicCode'),
    headSupervisor: formData.get('headSupervisor'),
    location: formData.get('location'),
    affiliatedInstitution: formData.get('affiliatedInstitution'),
    name: formData.get('name'),
    email: formData.get('email'),
    password: formData.get('password'),
  });

  const { ipAddress, userAgent } = await getRequestMeta();

  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? 'Invalid input' };
  }

  const { clinicName, clinicCode, headSupervisor, location, affiliatedInstitution, name, email, password } =
    parsed.data;

  const existingUser = await controlDb.query.users.findFirst({ where: eq(users.email, email) });
  if (existingUser) {
    await logAuditEvent({
      action: AUDIT_ACTIONS.CLINIC_REGISTRATION_SUBMITTED,
      resourceType: 'clinic',
      success: false,
      failureReason: 'email_taken',
      ipAddress,
      userAgent,
    });
    return { error: 'An account with this email already exists.' };
  }

  const adminRole = await controlDb.query.roles.findFirst({ where: eq(roles.name, 'clinic_admin') });
  if (!adminRole) {
    return { error: 'Server is not configured correctly. Please contact support.' };
  }

  const { slug, dbIdentifier } = await uniqueClinicIdentifiers(clinicName);
  const { codeHash, codeIdentifierHash } = await hashClinicCode(clinicCode);
  const passwordHash = await hashPassword(password);

  const clinic = await controlDb.transaction(async (tx) => {
    const [clinic] = await tx
      .insert(clinics)
      .values({
        slug,
        name: clinicName,
        dbIdentifier,
        status: 'pending',
        headSupervisor,
        location,
        affiliatedInstitution: affiliatedInstitution || null,
        isActive: false,
      })
      .returning();

    await tx.insert(clinicCodes).values({
      clinicId: clinic.id,
      codeHash,
      codeIdentifierHash,
      label: 'Founding registration code',
    });

    const [user] = await tx.insert(users).values({ email, passwordHash, name }).returning();

    await tx.insert(clinicMemberships).values({
      userId: user.id,
      clinicId: clinic.id,
      roleId: adminRole.id,
      status: 'pending',
    });

    return clinic;
  });

  await logAuditEvent({
    clinicId: clinic.id,
    action: AUDIT_ACTIONS.CLINIC_REGISTRATION_SUBMITTED,
    resourceType: 'clinic',
    resourceId: clinic.id,
    success: true,
    ipAddress,
    userAgent,
  });

  await sendWelcomeEmail(email, name);

  const settings = await getPlatformSettings();
  if (settings.notificationEmail) {
    const reviewUrl = `${process.env.APP_URL ?? ''}/admin/clinics`;
    await sendClinicRegistrationNotification(settings.notificationEmail, clinicName, reviewUrl);
  }

  return { success: true };
}

export async function loginAction(_prevState: AuthActionState, formData: FormData): Promise<AuthActionState> {
  const parsed = loginSchema.safeParse({
    email: formData.get('email'),
    password: formData.get('password'),
  });

  const { ipAddress, userAgent } = await getRequestMeta();

  if (!parsed.success) {
    return { error: parsed.error.issues[0]?.message ?? 'Invalid input' };
  }

  const { email, password } = parsed.data;

  const user = await controlDb.query.users.findFirst({ where: eq(users.email, email) });

  const passwordValid = user ? await verifyPassword(user.passwordHash, password) : false;

  if (!user || !user.isActive || !passwordValid) {
    await logAuditEvent({
      actorUserId: user?.id ?? null,
      action: AUDIT_ACTIONS.LOGIN_FAILURE,
      resourceType: 'user',
      resourceId: user?.id,
      success: false,
      failureReason: !user ? 'no_such_user' : !user.isActive ? 'account_disabled' : 'bad_password',
      ipAddress,
      userAgent,
    });
    return { error: 'Invalid email or password.' };
  }

  await logAuditEvent({
    actorUserId: user.id,
    action: AUDIT_ACTIONS.LOGIN_SUCCESS,
    resourceType: 'user',
    resourceId: user.id,
    success: true,
    ipAddress,
    userAgent,
  });

  const rawToken = await createSession({ userId: user.id, ipAddress, userAgent });
  await setSessionCookie(rawToken);

  // Patients have their own home (the portal); staff/admins go to the dashboard.
  const patientLink = await controlDb.query.patientLinks.findFirst({
    where: eq(patientLinks.userId, user.id),
  });
  redirect(patientLink ? '/patient-portal' : '/dashboard');
}

export async function logoutAction(): Promise<void> {
  const token = await getSessionTokenFromCookies();

  if (token) {
    const { ipAddress, userAgent } = await getRequestMeta();
    const session = await getSessionByToken(token);
    await invalidateSession(token);
    await logAuditEvent({
      actorUserId: session?.userId ?? null,
      action: AUDIT_ACTIONS.LOGOUT,
      resourceType: 'user',
      success: true,
      ipAddress,
      userAgent,
    });
  }

  await clearSessionCookie();
  redirect('/login');
}
