import { z } from 'zod';
import { ROLE_NAMES } from '@civica/permissions';

const passwordSchema = z.string().min(1, 'Password is required');

// Blocked domains that are clearly fake/temporary and would never correspond to
// a real staff member or patient. We block these at the boundary so every
// registered account has a real, reachable email address.
const BLOCKED_EMAIL_DOMAINS = new Set([
  'example.com',
  'example.org',
  'example.net',
  'test.com',
  'fake.com',
  'mailinator.com',
  'guerrillamail.com',
  'temp-mail.org',
  'throwam.com',
  'yopmail.com',
  'trashmail.com',
  'sharklasers.com',
  'guerrillamailblock.com',
]);

function isRealEmail(email: string): boolean {
  const domain = email.split('@')[1]?.toLowerCase() ?? '';
  return !BLOCKED_EMAIL_DOMAINS.has(domain);
}

const realEmailSchema = z
  .email('Enter a valid email address')
  .refine(isRealEmail, 'Please use a real email address.');

// Users joining an existing clinic may request to be its clinic_admin (e.g. a
// second/third admin who must be admitted by an existing admin) or an
// ordinary member. platform_admin is never requestable, and 'patient' is not a
// staff role -- patients register via the separate enrollment-code flow.
export const REQUESTABLE_ROLES = ROLE_NAMES.filter(
  (name) => name !== 'platform_admin' && name !== 'patient',
);

export const registerSchema = z.object({
  email: realEmailSchema,
  password: passwordSchema,
  name: z.string().min(1, 'Name is required').max(200),
  clinicCode: z.string().min(1, 'Clinic code is required').max(100),
  requestedRole: z.enum(REQUESTABLE_ROLES).default('member'),
});

export const loginSchema = z.object({
  email: z.email('Enter a valid email address'),
  password: z.string().min(1, 'Password is required'),
});

export const registerClinicSchema = z.object({
  clinicName: z.string().min(1, 'Clinic name is required').max(200),
  clinicCode: z.string().min(6, 'Clinic code must be at least 6 characters').max(100),
  headSupervisor: z.string().min(1, 'Head supervisor is required').max(200),
  location: z.string().min(1, 'Location is required').max(200),
  affiliatedInstitution: z.string().max(200).optional().or(z.literal('')),
  name: z.string().min(1, 'Your name is required').max(200),
  email: realEmailSchema,
  password: passwordSchema,
});

// Patients register with a per-patient enrollment code (generated by staff in
// the EMR). The code is the authoritative chart link; name/email are an extra
// soft cross-check. No clinic code and no requestable role here.
export const registerPatientSchema = z.object({
  enrollmentCode: z.string().min(1, 'Enrollment code is required').max(100),
  name: z.string().min(1, 'Name is required').max(200),
  email: realEmailSchema,
  password: passwordSchema,
});

export type RegisterInput = z.infer<typeof registerSchema>;
export type LoginInput = z.infer<typeof loginSchema>;
export type RegisterClinicInput = z.infer<typeof registerClinicSchema>;
export type RegisterPatientInput = z.infer<typeof registerPatientSchema>;
